services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    environment:
      - ACCEPT_EULA="Y"
      # - SA_PASSWORD="P@ssw0rd"
      - MSSQL_SA_PASSWORD="P@ssw0rd"
      # - MSSQL_PID="Developer"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql

volumes:
  my-volume:
